### ISSUE TITLE
Hydrogen remix upgrade stopped rendering site

### ISSUE THREAD

**Issue by zanedev** [netlify/hydrogen-platform#104]
We upgraded our working hydrogen site on netlify to the latest Hydrogen based on Remix `"@shopify/hydrogen": "^2023.1.4",` and the site stopped rendering with page not found. It builds fine but every page is not found even though it works fine locally. Is there some changes needed in the plugin after the latest hydrogen remix upgrade?

<img width="457" alt="image" src="https://user-images.githubusercontent.com/817344/219967627-e640e17e-90a6-448b-961b-d67bdb9fa3bd.png">

**Comment by ascorbic** [comment]
Hey. Yes, you need to switch it to being a Remix site, and enable the Netlify adapter. It's effectively a new framework. We will be updating our docs and template to show how to migrate, but for now your best bet is to look at [our existing Remix template](https://github.com/remix-run/remix/tree/main/templates/netlify) and copy the server and config files. This template uses the regular Netlify Functions rather than Edge Functions, but we will be releasing a new edge adapter soon.

**Comment by zanedev** [comment]
Thanks @ascorbic I will give it a try. Any idea when the new edge adapter will be ready?

@sarahetter should we leave this issue open until the docs are updated and / or the new edge adapter is released?

**Comment by zanedev** [comment]
Sorry to keep bumping this but we tried using the remix template with no luck. It seems like there is more to do with `createRequestHandler` for a hydrogen site on remix. Any idea on when the docs will be updated or the new edge handler will be ready? I am asking because we are ready to finally go live after the painful Hydrogen upgrade / migration and this is the only thing holding us up. Thanks.

**Comment by nickytonline** [comment]
@zanedev, yeah the Remix template is about using Remix directly via an adapter that creates the request handler like you mentioned.

I spent a small amount of time to see if plugging in our adapter would make things work, but it doesn't. This requires more investigation.

**Comment by zanedev** [comment]
Okay thanks, I look forward to the official release!
