### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ascorbic** [netlify/hydrogen-platform#32]
We need some form of tests added to this, though first we need to investigate which sort of tests would help.

**Comment by nickytonline** [comment]
Low priority for now

**Comment by MarcL** [comment]
Thanks to a great discussion with @ascorbic earlier, he suggested we should look to add upstream tests in the [shopify/hydrogen](https://github.com/Shopify/hydrogen/) project.

The [current tests](https://github.com/Shopify/hydrogen/blob/v1.x-2022-07/.github/workflows/deployments.yml#L106) only check that the Netlify site is deployed via the [health check script](https://github.com/Shopify/hydrogen/blob/v1.x-2022-07/scripts/health-check.js).

We could look to add additional integration or E2E tests to confirm that the page, images, and styles load and that the page renders some content. By adding the tests to Shopify's repo, we'd benefit from any upstream test failures being fixed by their team.

Their existing E2E test cases are [here](https://github.com/Shopify/hydrogen/blob/v1.x-2022-07/packages/playground/server-components/tests/e2e-test-cases.ts).
